server:
  port: 8080
spring:
  redis:
    host: localhost
  application:
    name: "SaldosYMovimientos"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
adapter:
  saldos:
    url: "https://eq6-transaction.getsandbox.com:443/balance"
  movimientos:
    url: "https://eq6-transactions.getsandbox.com/v1/operations/consult-services/retrieve-transaction"
